### PR TITLE
Add geom_tile to CoveragePlot to visualize Tn5 cuts in sliding windows

### PR DESCRIPTION
**Pull request by Puriney**
# Goal
This is related to issue #166 enabling `CoveragePlot` to visualize the presence of Tn5 cuts in single-cells across genomic sliding windows.

# Demo result after this PR is merged

The tile plots by `geom_tile` will be seamlessly added below the signal coverage panel. The cell groups, group levels, and colors of tile plots are as same as the signal coverage panel.

image

# What's been changed
- Two helper functions `ScCutMatrix` and `ScCutTilePlot ` are added in the <kbd>R/utilities.R</kbd> file.
- Two new parameters `add_tile` and `n_cells_per_group` are added in the `SingleCoveragePlot` and `CoveragePlot` main functions. The parameters are used to control whether to draw the tile panel and how many random cells to visualize.

# How
I propagate the sliding window along the matrix returned by the `CutMatrix` function.

Note that the width of the sliding window uses the original `window` parameter in `SingleCoveragePlot` to keep consistency.

```
[-------------------]: cells x 1_big_region_of_interest.
[-----][-----][-----]: cells x 3_sliding_windows
[  o      o      o  ]: cells x 3_values
```

# Note
In the `SingleCoveragePlot` function, you use "if/else" to explicitly control adding coverage panel, peak.plot, and gene.plot. The motivation seems to be that remove the x-axis elements of the coverage panel as long as either peak or gene plot is requested by users. Without breaking your codes too much, I simply append these lines (https://github.com/Puriney/signac/blob/249ca075ffb8fe7e2ae9870670d243511b2696e0/R/visualization.R#L312-L329) to do the same goal. Feel free to modify because I did not save your colorings of the peak and gene panel.

# Try this PR without installation

I used `devtools::load_all` to mimic loading the new package.  

```R
# library(Signac)
library(Seurat)
library(GenomeInfoDb)
library(EnsDb.Hsapiens.v75)
library(ggplot2)
library(patchwork)
library(tidyverse)
library(ggpubr)
set.seed(1234)
library(reshape2)
library(dplyr)

library(devtools)
devtools::load_all(path="/volumes/lab/users/yyan/apps/signac")


setwd('./') ## Change to your working dirs with all the tutorial files available
if (file.exists('pbmc.rds')){
  pbmc <- readRDS('pbmc.rds')
} else {
  counts <- Read10X_h5(filename = "./atac_v1_pbmc_10k_filtered_peak_bc_matrix.h5")
  metadata <- read.csv(
    file = "./atac_v1_pbmc_10k_singlecell.csv",
    header = TRUE,
    row.names = 1
  )
  pbmc <- CreateSeuratObject(
    counts = counts,
    assay = 'peaks',
    project = 'ATAC',
    min.cells = 1,
    meta.data = metadata
  )
  fragment.path <- './atac_v1_pbmc_10k_fragments.tsv.gz'
  pbmc <- SetFragments(
    object = pbmc,
    file = fragment.path
  )
  
  # Make dummy groups. Note: C<A<B is the order to highlight the factor is understood.
  pbmc$dummy_groups <- factor(LETTERS[c(1:ncol(pbmc) %% 3) + 1], levels = c('C', 'A', 'B'))
  print(table(pbmc$dummy_groups))
  saveRDS(pbmc, 'pbmc.rds')
} 
#-------------------------- Demo --------------------------  
gtrack <- genes(EnsDb.Hsapiens.v75)
seqlevelsStyle(gtrack) <- 'UCSC'
n_cells <- 120
set.seed(42)
region_check <- 'chr14-99738300-99738599'
region_check <- 'chr14-99599824-99759327'
region_check <- StringToGRanges(region_check)
region_sliding_windows <- slidingWindows(region_check, 
                                         width = 201, step=201)
region_sliding_windows <- unlist(region_sliding_windows)

## No cell grouping (Expose my logics before packaging code)
viz_sc_names <- sample(Cells(pbmc), size = n_cells, replace = F)
ppt <- CoveragePlot(
  object = pbmc,
  region = region_check,
  peaks = StringToGRanges(rownames(pbmc), sep = c(':', '-')),
  annotation = gtrack,
  scale.factor = 1e7,
  extend.upstream = 0,
  extend.downstream = 0)

mat <- ScCutMatrix(pbmc, region = region_check, cells = viz_sc_names, 
                   window_size = 201)
dim(mat)
tile_plot_b <- ScCutTilePlot(
  mat, gloc_lim = c(start(region_check), end(region_check)))

print(tile_plot_b + scale_fill_manual(values='red'))
ppt2 <- ppt[[1]] + tile_plot_b + 
  ppt[[2]] + ppt[[3]] +
  plot_layout(ncol = 1, heights = c(5, 1, 1, 1))
ggsave('cov1.png', ppt2, width = 10, height = 7)

## Cell groupings (Expose my logics before packaging code)
class(pbmc$dummy_groups)
viz_sc2grp <- pbmc[[]] %>%
  rownames_to_column(var='cname')%>%
  dplyr::group_by_at('dummy_groups') %>%
  dplyr::sample_n(n_cells) %>%
  select_at(c('cname', 'dummy_groups')) %>%
  deframe()
class(viz_sc2grp)
ppt <- CoveragePlot(
  object = pbmc,
  region = region_check,
  group.by = 'dummy_groups',
  peaks = StringToGRanges(rownames(pbmc), sep = c(':', '-')),
  annotation = gtrack,
  scale.factor = 1e7,
  extend.upstream = 0,
  extend.downstream = 0)

mat <- ScCutMatrix(pbmc, region = region_check, 
                   cells = names(viz_sc2grp))
dim(mat)
tile_plot_b <- ScCutTilePlot(
  mat, gloc_lim = c(start(region_check), end(region_check)),
  cells_group = viz_sc2grp)

print(tile_plot_b)

ppt2 <- ppt[[1]] + tile_plot_b + 
  ppt[[2]] + ppt[[3]] +
  plot_layout(ncol = 1, heights = c(10, 10/5, 1, 1))
ggsave('cov2.png', ppt2, width = 10, height = 7)

## New Function -- single region (Packaged code)
set.seed(42)
ppt <- CoveragePlot(
  object = pbmc,
  region = region_check,
  group.by = 'dummy_groups',
  peaks = StringToGRanges(rownames(pbmc), sep = c(':', '-')),
  annotation = gtrack,
  scale.factor = 1e7,
  extend.upstream = 0,
  extend.downstream = 0,
  add_tile = T, n_cells_per_group = 120)
ggsave('cov3.png', ppt, width = 10, height = 10)


## New Function -- a list of regions (Package code)
set.seed(42)
region_check_x <- c('chr14-99599824-99759327', 'chr6-44025105-44028184 ')
region_check_x <- StringToGRanges(region_check_x)
ppt <- CoveragePlot(
  object = pbmc,
  region = region_check_x,
  group.by = 'dummy_groups',
  peaks = StringToGRanges(rownames(pbmc), sep = c(':', '-')),
  annotation = gtrack,
  scale.factor = 1e7,
  extend.upstream = 0,
  extend.downstream = 0,
  add_tile = T, n_cells_per_group = 120)
ggsave('cov4.png', ppt, width = 10, height = 10)
```

### CODE REVIEW

**Comment by Puriney** [comment]
## cov1.png
image

## cov2.png
image

## cov3.png
image

## cov4.png
image

**Comment by Puriney** [comment]
The package itself can be installed and successfully used. But the R-CMD-check still showed those errors. Since the `globalVariables` for pkg dev is involved, the conflict might need your help. 

```
❯ checking R code for possible problems ... NOTE
  ScCutTilePlot: no visible global function definition for ‘%>%’
  ScCutTilePlot: no visible binding for global variable ‘cname’
  ScCutTilePlot: no visible binding for global variable ‘count’
  SingleCoveragePlot: no visible global function definition for ‘%>%’
  Undefined global functions or variables:
    %>% cname count
```

**Comment by timoast** [comment]
Thanks for the PR @Puriney, the plots look great! I'll take a look at the code over the next few days

**Comment by timoast** [comment]
@Puriney I made a few minor changes to get R CMD check to pass. One minor thing is that it would be good to choose the cells that are shown based on the total number of fragments they have in the region. I'm actually getting ready to release a major update that changes a lot of how CoveragePlot is organized, so I'll merge this for now and try to keep working on it in the new release. Thanks again for your contribution!

**Comment by Puriney** [comment]
Looking forward to the update. Thank you again for examing and merging my PR.

**Pull request merged**
