### PR TITLE
Add sparse spearman correlation

### PR DESCRIPTION
**Pull request by saketkc**
Adds an extra argument to run spearman correlation on `LinkPeaks()`

```r
n_peaks <- 5000
n_cells <- 1000
X.dense <- replicate(n_cells, rbinom(n = n_peaks, size = 1, prob = 0.1))
X.sparse <- Matrix::Matrix(X.dense, sparse = TRUE)
system.time(corX.sparse <- SparseSpearmanCor(X.sparse))
norm(corX.dense - corX.sparse, type = "2")

```

### CODE REVIEW

**Comment by timoast** [comment]
I tested this with the multiome dataset used in the [vignette](https://satijalab.org/signac/articles/pbmc_multiomic.html), and it works but is quite slow. Finding links for 2 genes takes approximately:
* 7 s for Pearson (sparse correlation)
* 3 min 30 s for Spearman (this PR)
* 30 s for coercing to a dense matrix and running `cor()` with `method="spearman"`

Most of the time is spent in the `SparsifiedRanks()` function, so I think we need to either find a way to speed that up, or we can implement Spearman using `cor()` instead (which will also use more memory, but it shouldn't be much of a problem since this is done one gene at a time)

**Comment by saketkc** [comment]
I should have done some stringent time benchmarks as it seemed to perform better with some smaller matrices. 
But, agreed it is not faster even if it takes less memory. Though, it would be good to think of ideas to speed up the SparsifyRanks function anyway. I will close this for now.  [Here](https://saket-choudhary.me/blog/2022/03/09/sparsespearman/) is a post summarizing the idea, if anyone bumps into this and has ideas to speed it up.

**Comment by saketkc** [comment]
A faster implementation was indeed possible:

```r
SparsifiedRanks2 <- function(X) {
  if (class(X.sparse)[1] != "dgCMatrix") {
    X <- as(object = X, Class = "dgCMatrix")
  }
  non_zeros_per_col <- diff(x = X@p)
  n_zeros_per_col <- nrow(x = X) - non_zeros_per_col
  offsets <- (n_zeros_per_col - 1) / 2
  x <- X@x
  ## split entries to columns
  col_lst <- split(x = x, f = rep.int(1:ncol(X), non_zeros_per_col))
  ## calculate sparsified ranks and do shifting
  sparsified_ranks <- unlist(x = lapply(X = seq_along(col_lst), 
                                        FUN = function(i) rank(x = col_lst[[i]]) + offsets[i]))
  ## Create template rank matrix
  X.ranks <- X
  X.ranks@x <- sparsified_ranks
  return(X.ranks)
}



SparseSpearmanCor2 <- function(X, Y = NULL, cov = FALSE) {

  # Get sparsified ranks
  rankX <- SparsifiedRanks2(X)
  if (is.null(Y)){
    # Calculate pearson correlation on rank matrices
    return (corSparse(X=rankX, cov=cov))
    }
  rankY <- SparsifiedRanks2(Y)
  return(corSparse( X = rankX, Y = rankY, cov = cov))
}
```


image

**Comment by timoast** [comment]
Thanks @saketkc, nice speedup!

**Pull request merged**
